=== yukuku/androidbible/tools/prog/wordsend/BibleBookInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Michael Paul Johnson (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BibleBookInfo">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Book">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sfmTla" type="xs:string"/>
							<xs:element name="osisName" type="xs:string"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="shortName" type="xs:string"/>
							<xs:element name="sortOrder" type="xs:integer"/>
							<xs:element name="numChapters" type="xs:integer"/>
						</xs:sequence>
						<xs:attribute name="testament" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yukuku/androidbible/AlkitabConverter/prog/wordsend/BibleBookInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Michael Paul Johnson (private) -->
<BibleBookInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sil\onyx\BibleBookInfo.xsd">
	<Book testament="x">
		<sfmTla>FRT</sfmTla>
		<osisName>Preface</osisName>
		<name>Front matter</name>
		<shortName>Front</shortName>
		<sortOrder>0</sortOrder>
		<numChapters>1</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>GEN</sfmTla>
		<osisName>Gen</osisName>
		<name>Genesis</name>
		<shortName>Genesis</shortName>
		<sortOrder>1</sortOrder>
		<numChapters>50</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>EXO</sfmTla>
		<osisName>Exod</osisName>
		<name>Exodus</name>
		<shortName>Exodus</shortName>
		<sortOrder>2</sortOrder>
		<numChapters>40</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>LEV</sfmTla>
		<osisName>Lev</osisName>
		<name>Leviticus</name>
		<shortName>Leviticus</shortName>
		<sortOrder>3</sortOrder>
		<numChapters>27</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>NUM</sfmTla>
		<osisName>Num</osisName>
		<name>Numbers</name>
		<shortName>Numbers</shortName>
		<sortOrder>4</sortOrder>
		<numChapters>36</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>DEU</sfmTla>
		<osisName>Deut</osisName>
		<name>Deuteronomy</name>
		<shortName>Deuteronomy</shortName>
		<sortOrder>5</sortOrder>
		<numChapters>34</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JOS</sfmTla>
		<osisName>Josh</osisName>
		<name>Joshua</name>
		<shortName>Joshua</shortName>
		<sortOrder>6</sortOrder>
		<numChapters>24</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JDG</sfmTla>
		<osisName>Judg</osisName>
		<name>Judges</name>
		<shortName>Judges</shortName>
		<sortOrder>7</sortOrder>
		<numChapters>21</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>RUT</sfmTla>
		<osisName>Ruth</osisName>
		<name>Ruth</name>
		<shortName>Ruth</shortName>
		<sortOrder>8</sortOrder>
		<numChapters>4</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>1SA</sfmTla>
		<osisName>1Sam</osisName>
		<name>The First Book of Samuel</name>
		<shortName>1 Samuel</shortName>
		<sortOrder>9</sortOrder>
		<numChapters>31</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>2SA</sfmTla>
		<osisName>2Sam</osisName>
		<name>The Second Book of Samuel</name>
		<shortName>2 Samuel</shortName>
		<sortOrder>10</sortOrder>
		<numChapters>24</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>1KI</sfmTla>
		<osisName>1Kgs</osisName>
		<name>The First Book of Kings</name>
		<shortName>1 Kings</shortName>
		<sortOrder>11</sortOrder>
		<numChapters>22</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>2KI</sfmTla>
		<osisName>2Kgs</osisName>
		<name>The Second Book of Kings</name>
		<shortName>2 Kings</shortName>
		<sortOrder>12</sortOrder>
		<numChapters>25</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>1CH</sfmTla>
		<osisName>1Chr</osisName>
		<name>The First Book of Chronicles</name>
		<shortName>1 Chronicles</shortName>
		<sortOrder>13</sortOrder>
		<numChapters>29</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>2CH</sfmTla>
		<osisName>2Chr</osisName>
		<name>The Second Book of Chronicles</name>
		<shortName>2 Chronicles</shortName>
		<sortOrder>14</sortOrder>
		<numChapters>36</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>EZR</sfmTla>
		<osisName>Ezra</osisName>
		<name>Ezra</name>
		<shortName>Ezra</shortName>
		<sortOrder>15</sortOrder>
		<numChapters>10</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>NEH</sfmTla>
		<osisName>Neh</osisName>
		<name>Nehemiah</name>
		<shortName>Nehemiah</shortName>
		<sortOrder>16</sortOrder>
		<numChapters>13</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>EST</sfmTla>
		<osisName>Esther</osisName>
		<name>Esther</name>
		<shortName>Esther</shortName>
		<sortOrder>17</sortOrder>
		<numChapters>10</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JOB</sfmTla>
		<osisName>Job</osisName>
		<name>Job</name>
		<shortName>Job</shortName>
		<sortOrder>18</sortOrder>
		<numChapters>42</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>PSA</sfmTla>
		<osisName>Pss</osisName>
		<name>Psalms</name>
		<shortName>Psalms</shortName>
		<sortOrder>19</sortOrder>
		<numChapters>150</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>PRO</sfmTla>
		<osisName>Prov</osisName>
		<name>Proverbs</name>
		<shortName>Proverbs</shortName>
		<sortOrder>20</sortOrder>
		<numChapters>31</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>ECC</sfmTla>
		<osisName>Eccl</osisName>
		<name>Ecclesiastes</name>
		<shortName>Ecclesiastes</shortName>
		<sortOrder>21</sortOrder>
		<numChapters>12</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>SNG</sfmTla>
		<osisName>Song</osisName>
		<name>Song of Solomon</name>
		<shortName>Song of Solomon</shortName>
		<sortOrder>22</sortOrder>
		<numChapters>8</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>ISA</sfmTla>
		<osisName>Isa</osisName>
		<name>Isaiah</name>
		<shortName>Isaiah</shortName>
		<sortOrder>23</sortOrder>
		<numChapters>66</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JER</sfmTla>
		<osisName>Jer</osisName>
		<name>Jeremiah</name>
		<shortName>Jeremiah</shortName>
		<sortOrder>24</sortOrder>
		<numChapters>52</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>LAM</sfmTla>
		<osisName>Lam</osisName>
		<name>Lamentations</name>
		<shortName>Lamentations</shortName>
		<sortOrder>25</sortOrder>
		<numChapters>5</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>EZK</sfmTla>
		<osisName>Ezek</osisName>
		<name>Ezekiel</name>
		<shortName>Ezekiel</shortName>
		<sortOrder>26</sortOrder>
		<numChapters>48</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>DAN</sfmTla>
		<osisName>Dan</osisName>
		<name>Daniel</name>
		<shortName>Daniel</shortName>
		<sortOrder>27</sortOrder>
		<numChapters>12</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>HOS</sfmTla>
		<osisName>Hos</osisName>
		<name>Hosea</name>
		<shortName>Hosea</shortName>
		<sortOrder>28</sortOrder>
		<numChapters>14</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JOL</sfmTla>
		<osisName>Joel</osisName>
		<name>Joel</name>
		<shortName>Joel</shortName>
		<sortOrder>29</sortOrder>
		<numChapters>3</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>AMO</sfmTla>
		<osisName>Amos</osisName>
		<name>Amos</name>
		<shortName>Amos</shortName>
		<sortOrder>30</sortOrder>
		<numChapters>9</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>OBA</sfmTla>
		<osisName>Obad</osisName>
		<name>Obadiah</name>
		<shortName>Obadiah</shortName>
		<sortOrder>31</sortOrder>
		<numChapters>1</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>JON</sfmTla>
		<osisName>Jonah</osisName>
		<name>Jonah</name>
		<shortName>Jonah</shortName>
		<sortOrder>32</sortOrder>
		<numChapters>4</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>MIC</sfmTla>
		<osisName>Mic</osisName>
		<name>Micah</name>
		<shortName>Micah</shortName>
		<sortOrder>33</sortOrder>
		<numChapters>7</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>NAM</sfmTla>
		<osisName>Nah</osisName>
		<name>Nahum</name>
		<shortName>Nahum</shortName>
		<sortOrder>34</sortOrder>
		<numChapters>3</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>HAB</sfmTla>
		<osisName>Hab</osisName>
		<name>Habakkuk</name>
		<shortName>Habakkuk</shortName>
		<sortOrder>35</sortOrder>
		<numChapters>3</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>ZEP</sfmTla>
		<osisName>Zeph</osisName>
		<name>Zephaniah</name>
		<shortName>Zephaniah</shortName>
		<sortOrder>36</sortOrder>
		<numChapters>3</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>HAG</sfmTla>
		<osisName>Hag</osisName>
		<name>Haggai</name>
		<shortName>Haggai</shortName>
		<sortOrder>37</sortOrder>
		<numChapters>2</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>ZEC</sfmTla>
		<osisName>Zech</osisName>
		<name>Zechariah</name>
		<shortName>Zechariah</shortName>
		<sortOrder>38</sortOrder>
		<numChapters>14</numChapters>
	</Book>
	<Book testament="o">
		<sfmTla>MAL</sfmTla>
		<osisName>Mal</osisName>
		<name>Malachi</name>
		<shortName>Malachi</shortName>
		<sortOrder>39</sortOrder>
		<numChapters>4</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>TOB</sfmTla>
		<osisName>Tob</osisName>
		<name>Tobit</name>
		<shortName>Tobit</shortName>
		<sortOrder>40</sortOrder>
		<numChapters>14</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>JDT</sfmTla>
		<osisName>Jdt</osisName>
		<name>Judith</name>
		<shortName>Judith</shortName>
		<sortOrder>41</sortOrder>
		<numChapters>16</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>ESG</sfmTla>
		<osisName>AddEsth</osisName>
		<name>Esther (Greek)</name>
		<shortName>Esther (Greek)</shortName>
		<sortOrder>42</sortOrder>
		<numChapters>16</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>WIS</sfmTla>
		<osisName>Wis</osisName>
		<name>Wisdom of Solomon</name>
		<shortName>Wisdom</shortName>
		<sortOrder>43</sortOrder>
		<numChapters>19</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>SIR</sfmTla>
		<osisName>Sir</osisName>
		<name>Sirach</name>
		<shortName>Sirach</shortName>
		<sortOrder>44</sortOrder>
		<numChapters>51</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>BAR</sfmTla>
		<osisName>Bar</osisName>
		<name>Baruch</name>
		<shortName>Baruch</shortName>
		<sortOrder>45</sortOrder>
		<numChapters>5</numChapters>
	</Book>
	<Book testament="a">
		<sfmTla>LJE</sfmTla>
		<osisName>EpJer</osisName>
		<name>Letter of Jeremiah</name>
